### ISSUE TITLE
echo-demo 注册后无相关pod启动，plugin list 中无此条目

### ISSUE THREAD

**Issue by lunz1207** [tkeel-io/cli#14]
## Expected Behavior

plugin  list 中有 echo demo，且PLUGINSTATUS 为 ACTIVE

## Actual Behavior

plugin  list 中无echo demo
```
root@i-migv83pb:~# tkeel plugin list
  NAME     NAMESPACE  HEALTHY  STATUS   PLUGINSTATUS  REPLICAS  VERSION  AGE  CREATED              
  auth     testing    True     Running  UNKNOWN       1         0.0.1    33m  2021-10-18 10:26.42  
  keel     testing    True     Running  UNKNOWN       1         0.0.1    33m  2021-10-18 10:26.42  
  plugins  testing    True     Running  UNKNOWN       1         0.0.1    33m  2021-10-18 10:26.42 
```

## Steps to Reproduce the Problem

1、tkeel 初始化安装
`tkeel init -k -n testing --wait --debug`

2、echo demo 注册
`tkeel plugin register echo-demo`

3、查看差距状态
`tkeel plugin list -k`

## Release Note

RELEASE NOTE:

**Comment by OdysseusC** [comment]
现在 **cli** 注册行为仅为访问平台的 **Plugins** 插件的 `/register` 端点，未包含启动相关 **Pod** 的内容。

 需要 @imneov 确定外部插件的注册流程，是否应完善如下：
1. 指定 chart 包地址。
2. 修改对应 Values。
3. 通过 **cli** 将**Pod**拉起来。
4. 请求 **Plugins** 插件的 `/register` 端点，完成注册流程。

**Comment by imneov** [comment]
这个流程是

利用 helm 安装 echo-demo
利用 tkeel 注册该插件

**Comment by imneov** [comment]
后期会考虑将 helm 安装流程放到 cli 中
