### ISSUE TITLE
[Readme] Doubts about deploying plugins

### ISSUE THREAD

**Issue by uptutu** [tkeel-io/cli#22]
## 部署插件疑惑
README 文档中部署插件（deploy plugin）部分，现在是跳转到了 dapr 的启动程序的文档中，CLI 既然作为一个用户入口，我觉得应该有一套完善的命令，而不是在这个部分使用 dapr 去做底层的实现。

作为一个傻瓜式的开发者，我只想通过 tkeel 帮助我快速搭建我的服务，但是这样的话我就还需要去学习 dapr ，成本太高。

**Comment by imneov** [comment]
Maybe we can add dapr helm charts as a dependency of tkeel.

@OdysseusC @liuzhen21
