### ISSUE TITLE
插件不会安装到指定命名空间

### ISSUE THREAD

**Issue by lunz1207** [tkeel-io/cli#30]
日志如下
`➜  ~ tkeel plugin list -i
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION                      
tkeel/auth                   	0.1.0        	1.16.0     	A Helm chart for Kubernetes      
tkeel/core                   	0.1.0        	1.16.0     	A Helm chart for Kubernetes      
tkeel/iothub                 	0.1.0        	1.16.0     	A Helm chart for Kubernetes      
tkeel/keel                   	0.1.0        	1.16.0     	A Helm chart for Kubernetes      
tkeel/plugins                	0.1.0        	1.16.0     	A Helm chart for Kubernetes      
tkeel/tkeel-middleware       	0.1.0        	1.16.0     	A Helm chart for tKeel middleware
tkeel/tkeel-plugin-components	0.1.0        	1.16.0     	A Helm chart for Kubernetes      

➜  ~ tkeel plugin install tkeel/auth auth-testing -n testing
✅  Install "tkeel/auth" success! It's named "auth-testing" in k8s
➜  ~ helm list -n testing
NAME        	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART     	APP VERSION
auth-testing	default  	1       	2021-11-25 16:00:17.75445 +0800 CST 	deployed	auth-0.1.0	1.16.0     
dapr        	testing  	1       	2021-11-25 14:47:14.495482 +0800 CST	deployed	dapr-1.5.0	1.5.0      
➜  ~ k get pod 
NAME                    READY   STATUS             RESTARTS      AGE
auth-5fd94dfdbf-7xppc   1/2     CrashLoopBackOff   1 (17s ago)   23s
➜  ~ k get pod -n testing
NAME                                    READY   STATUS    RESTARTS   AGE
dapr-dashboard-854cf9ccb4-sqf5s         1/1     Running   0          73m
dapr-operator-6c8cc99949-kzw2v          1/1     Running   0          73m
dapr-placement-server-0                 1/1     Running   0          73m
dapr-sentry-6478979b47-7rbjv            1/1     Running   0          73m
dapr-sidecar-injector-f4cd47cfd-68wzc   1/1     Running   0          73m
`

**Comment by uptutu** [comment]
fixed in #31 . Thx for your feedback.
