### ISSUE TITLE
【feature】tkeel cli 加入dubug 模式

### ISSUE THREAD

**Issue by lunz1207** [tkeel-io/cli#5]
tkeel init 时，有时候会出现 timed out waiting for the condition，如下图。增加debug模式方便排查问题 。
![image](https://user-images.githubusercontent.com/26782305/136649079-9ba3ab13-5b12-42b8-89a2-13a952f106d8.png)

**Comment by imneov** [comment]
Close by https://github.com/tkeel-io/cli/pull/7
