### ISSUE TITLE
Can not uninstall batch

### ISSUE THREAD

**Issue by jia-zhengwei** [tkeel-io/cli#50]
**Describe the bug**

1.  Can not uninstall batch
2.  Whether need to add `-k` in cmd or not ？
3.  Whether need to add `-n keel-system` ?

**To Reproduce**

```sh
tkeel plugin uninstall  tkeel-device iothub
```

**Expected behavior**

1. batch uninstall supported
2. `-k` could be optional
3. add '-n keel-system' by daeault

**Comment by imneov** [comment]
At the moment, there is no plan to support uninstall batch
